<a href="https://colab.research.google.com/github/VitorGama10/Deep_Learning/blob/main/Deep_Learning_Pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tipos De Tensores
Voce pode criar tensores do Pytorch dd inumeras formas, vamos converte listas comuns do python em tensores do pytorch

In [29]:
import torch

lista = [[1,2,3], [4,5,6]]

tns = torch.Tensor(lista) # vai converte para o tipo padrao do pytorch
print(tns.dtype)
print(tns)


tns = torch.FloatTensor(lista) # o float q é o padrao q usamos
print(tns.dtype)
print(tns)


tns = torch.DoubleTensor(lista) # Um ponto flutuante com maior precisão
print(tns.dtype)
print(tns)


tns = torch.LongTensor(lista) # quando é necessario usar indeiros, e tem uma precisao maior pra quando querer operar com outras coisas
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


# Outras formas de instanciar tensores

A partir de arrays Numpy 

In [30]:
import numpy as np

arr = np.random.rand(3,4) # array aleatorio 
tns = torch.from_numpy(arr)  # convertendo para tensor 
print(arr)
print(tns)

# criei um array aleatorio e converti para um tensor

[[0.25764168 0.43788888 0.04090769 0.3709509 ]
 [0.21096431 0.72567913 0.27821294 0.09761351]
 [0.21966551 0.46839993 0.2629199  0.59998642]]
tensor([[0.2576, 0.4379, 0.0409, 0.3710],
        [0.2110, 0.7257, 0.2782, 0.0976],
        [0.2197, 0.4684, 0.2629, 0.6000]], dtype=torch.float64)


# Tensores inicializados 
Essas funçoes recebem como parametro o tamanho de cada dimensao do tensor.Aqui vamos conhecer as seguintes funcoes


In [31]:
tns1 = torch.ones(2,3) # com numeros 1
tns0 = torch.zeros(4,5) # com numeros zeros 
tnsr = torch.randn(3,3) # Numeros aleatorios

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[-0.2865,  0.5742,  0.4458],
        [-0.9914, -0.8793, -0.3130],
        [-0.2787,  1.3274,  1.5508]])


# Tensor para array numpy 

In [32]:
arr = tnsr.data.numpy()
print(arr)

[[-0.2864662   0.57416534  0.44581252]
 [-0.991421   -0.8792935  -0.3129629 ]
 [-0.2786739   1.3273712   1.5507952 ]]


# Indexação

De posse dessa informação, a indexacao é feita de forma similar a arrays numpy, atraves de sintaxe de colchetes '[ ]'

In [33]:
print(tnsr)
tnsr[0, 2] = - 10

print('')
print(tnsr)

print('') # da um espaco nos tensores
print(tnsr[0:2])

print('')
print(tnsr[:, 2]) # todos as linhas da coluna 2 (pegando uma fatia do meu tensor)

tensor([[-0.2865,  0.5742,  0.4458],
        [-0.9914, -0.8793, -0.3130],
        [-0.2787,  1.3274,  1.5508]])

tensor([[ -0.2865,   0.5742, -10.0000],
        [ -0.9914,  -0.8793,  -0.3130],
        [ -0.2787,   1.3274,   1.5508]])

tensor([[ -0.2865,   0.5742, -10.0000],
        [ -0.9914,  -0.8793,  -0.3130]])

tensor([-10.0000,  -0.3130,   1.5508])


# Operações com tensores
A função .item() utilizada anteriormente extrai o número de um tensor que possui um único valor, permitindo realizar as operações numéricas do Python. Caso o item não seja extraído, operações que envolvam tensores vão retornar novos tensores.

Vale ressaltar também que operações entre tensores são realizadas ponto a ponto, operando cada elemento (i, j) do tensor t1, com o elemento (i, j) do tensor t2.

In [34]:
tns = tnsr[0:2, :]
print(tns)
print(tns1)

print(torch.mm(tns, tns1.T))

tensor([[ -0.2865,   0.5742, -10.0000],
        [ -0.9914,  -0.8793,  -0.3130]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[-9.7123, -9.7123],
        [-2.1837, -2.1837]])


# Função .size() e .view()
Uma operações importantíssima na manipulação de tensores para Deep Learning é a reorganização das suas dimensões. Dessa forma podemos, por exemplo, linearizar um tensor n-dimensional.

In [35]:
tns = torch.randn(2,2,3)
print(tns)
print('')

# tamanho do meu tensor 
print(tns.size()) # quase mesma coisa q o shape, faz ver quantas linhas tem e quantas coluna 
tns = tns.view(12) # muda o jeito do tensor
print(tns)

tensor([[[ 2.9690,  1.8335, -0.1075],
         [-1.4542, -1.1373,  0.0560]],

        [[-1.1610,  0.0674,  0.3307],
         [ 1.0540,  1.1969, -0.5799]]])

torch.Size([2, 2, 3])
tensor([ 2.9690,  1.8335, -0.1075, -1.4542, -1.1373,  0.0560, -1.1610,  0.0674,
         0.3307,  1.0540,  1.1969, -0.5799])


In [36]:
# Outro Exemplo
tns = torch.randn(2,2,3)
print(tns)
print('')

# tamanho do meu tensor 
print(tns.size()) # quase mesma coisa q o shape, faz ver quantas linhas tem e quantas coluna 
tns = tns.view(4, 3) # muda o jeito do tensor
print(tns)

tensor([[[-1.5407, -1.4268,  1.4587],
         [-2.7717,  0.8312, -0.5598]],

        [[-0.3859, -1.9490,  0.8924],
         [ 0.0032, -0.7351,  0.0040]]])

torch.Size([2, 2, 3])
tensor([[-1.5407, -1.4268,  1.4587],
        [-2.7717,  0.8312, -0.5598],
        [-0.3859, -1.9490,  0.8924],
        [ 0.0032, -0.7351,  0.0040]])


# GPU Cast
Para que o seu script dê suporte a infraestruturas com e sem GPU, é importante definir o dispositivo no início do seu código de acordo com a verificação apresentada a seguir. Essa definição de dispositivo será utilizada toda vez que precisarmos subir valores na GPU, como os pesos da rede, os gradientes, etc.

In [46]:
import torch

tns = torch.randn(10) # criou um tensor com numeros aleatorios

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
    device = torch.device('cpu')
print('cuda é GPU: pra criar modelos maiores de redes neurais é extremamente importante esta na GPU e  pra resolver problema do mundo real tbm. {}'.format(device))

tns = tns.to(device)
print(tns)


cuda é GPU: pra criar modelos maiores de redes neurais é extremamente importante esta na GPU e  pra resolver problema do mundo real tbm. cuda
tensor([ 0.3739,  0.2028, -0.8977,  0.7115, -1.1410, -0.4834, -0.4905,  1.7877,
         0.7097, -1.3533], device='cuda:0')
